### ISSUE TITLE
Better solution for `for … in … if`

### ISSUE THREAD

**Issue by asaaki** [johannhof/rust-crawl#1]
Location: https://github.com/johannhof/rust-crawl/blob/6e074a88c392cbd59bf6ad31baafde95d909dc2f/src/main.rs#L28-L29

``` rust
for attr in tag.attrs {
    if attr.name.local.as_slice() == "href" {
```

Does anyone know a possible better solution for this?
The attributes collection is pretty small here, but in general such collections could be really huge, too.
Is there something like a `.find()`?
I've found [fn retain<F>(&mut self, f: F) ](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.retain), but this needs a mutable vector. Also it sounds pretty costly (perhaps less performant than just iterating and fetching the element in question via condition).

So what I'm basically asking is, how to short-circuit this whole process, since I know there will be only one matching element in this case and therefore it is pointless to iterate further after I've found it.

**Comment by asaaki** [comment]
Just found `break` for the loop:

``` rust
for attr in tag.attrs {
    if attr.name.local.as_slice() == "href" {
        // ...
        break;
    }
}
```

Which makes the iteration process much shorter already, as long as the `href` attribute is not in the last position, of course.

**Comment by asaaki** [comment]
Okay, after some digging, I found my find. :sweat_smile: 

``` rust
match tag.attrs.iter().find(|e| e.name.local.as_slice() == "href") {
    Some(attr) => { /* ... */ },
    None => {}
}
```

Doc: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.find

**Comment by johannhof** [comment]
Looks good!
